// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWbG24t3Z-0LwcfFSKOC5z0OQwQ1Gsu2Y',
    appId: '1:725646893210:web:d6c71935871f13e7fb7f23',
    messagingSenderId: '725646893210',
    projectId: 'movies-4c160',
    authDomain: 'movies-4c160.firebaseapp.com',
    databaseURL: 'https://movies-4c160-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movies-4c160.appspot.com',
    measurementId: 'G-HFFGS2K5B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxMS0zpo8uZpRa7QU9s8YVaL5z14B5lh8',
    appId: '1:725646893210:android:dade46e27a897606fb7f23',
    messagingSenderId: '725646893210',
    projectId: 'movies-4c160',
    databaseURL: 'https://movies-4c160-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movies-4c160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSGsCLVgJUKajDGR-hilUZ73ROkjUsBg',
    appId: '1:725646893210:ios:17cec67339d8f015fb7f23',
    messagingSenderId: '725646893210',
    projectId: 'movies-4c160',
    databaseURL: 'https://movies-4c160-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movies-4c160.appspot.com',
    iosBundleId: 'com.example.nexMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSGsCLVgJUKajDGR-hilUZ73ROkjUsBg',
    appId: '1:725646893210:ios:5fe0520cb61cdddffb7f23',
    messagingSenderId: '725646893210',
    projectId: 'movies-4c160',
    databaseURL: 'https://movies-4c160-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movies-4c160.appspot.com',
    iosBundleId: 'com.example.nexMovies.RunnerTests',
  );
}
